
import { GET_TRENDING_FEED, GET_TIMELINE, CREATE_POST } from './post';

export const GQL = {
    GET_TRENDING_FEED: GET_TRENDING_FEED,
    GET_TIMELINE: GET_TIMELINE,
    CREATE_POST: CREATE_POST
}