import { GET_TRENDING_FEED, GET_TIMELINE, CREATE_POST, GET_POST, CREATE_COMMENTS, SUBSCRIPTION_COMMENT_CREATED } from './post';
import { GET_MY_PROFILE, AUTHENTICATION, GET_PUBLIC_PROFILE, FOLLOW, UNFOLLOW, FOLLOW_RELATION, GET_PUBLIC_SNS_PROFILE } from './user';
import {
    SUGGESTING_TO_MENTION,
    UNREAD_MENTIONED_NOTIFICATION_COUNT,
    SUBSCRIPTION_UNREAD_MENTIONED_CREATED,
    MENTIONED_CREATED
} from './mention';

import { USER_ROBOT } from './robot';

export const GQL = {
    GET_TRENDING_FEED: GET_TRENDING_FEED,
    GET_TIMELINE: GET_TIMELINE,
    CREATE_POST: CREATE_POST,
    GET_MY_PROFILE: GET_MY_PROFILE,
    GET_POST: GET_POST,
    CREATE_COMMENTS: CREATE_COMMENTS,
    AUTHENTICATION: AUTHENTICATION,
    GET_PUBLIC_PROFILE: GET_PUBLIC_PROFILE,
    GET_PUBLIC_SNS_PROFILE: GET_PUBLIC_SNS_PROFILE,
    FOLLOW: FOLLOW,
    UNFOLLOW: UNFOLLOW,
    FOLLOW_RELATION: FOLLOW_RELATION,
    SUGGESTING_TO_MENTION: SUGGESTING_TO_MENTION,
    UNREAD_MENTIONED_NOTIFICATION_COUNT: UNREAD_MENTIONED_NOTIFICATION_COUNT,
    SUBSCRIPTION_UNREAD_MENTIONED_CREATED: SUBSCRIPTION_UNREAD_MENTIONED_CREATED,
    MENTIONED_CREATED: MENTIONED_CREATED,
    USER_ROBOT: USER_ROBOT,
    SUBSCRIPTION_COMMENT_CREATED: SUBSCRIPTION_COMMENT_CREATED,
}