
import { GET_TRENDING_FEED, GET_TIMELINE, CREATE_POST, GET_POST, CREATE_COMMENTS } from './post';
import { GET_MY_PROFILE, AUTHENTICATION, GET_PUBLIC_PROFILE, FOLLOW, UNFOLLOW, FOLLOW_RELATION } from './user';

export const GQL = {
    GET_TRENDING_FEED: GET_TRENDING_FEED,
    GET_TIMELINE: GET_TIMELINE,
    CREATE_POST: CREATE_POST,
    GET_MY_PROFILE: GET_MY_PROFILE,
    GET_POST: GET_POST,
    CREATE_COMMENTS: CREATE_COMMENTS,
    AUTHENTICATION: AUTHENTICATION,
    GET_PUBLIC_PROFILE: GET_PUBLIC_PROFILE,
    FOLLOW: FOLLOW,
    UNFOLLOW: UNFOLLOW,
    FOLLOW_RELATION: FOLLOW_RELATION

}